name: FaultPulse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  faultpulse:
    runs-on: ubuntu-latest

    steps:
      # 🧾 STEP 1 — Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # ⚙️ STEP 2 — Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 📦 STEP 3 — Install dependencies
      - name: Install dependencies
        run: npm install

      # 🚀 STEP 4 — Run FaultPulse
      - name: Run FaultPulse
        run: node core/runner.js https://example.com

      # 📤 STEP 5 — Upload report artifact
      - name: Upload FaultPulse Report
        uses: actions/upload-artifact@v4
        with:
          name: faultpulse-report
          path: reports/latest.json