name: CI Pipeline

on:
  push:
    branches:
      - main
      - test-bot
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug current directory
        run: pwd
        
      - name: List top-level files
        run: ls
        
      - name: Full structure
        run: ls -R  
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '18'   
        
      - name: Debug folders
        run: ls
        
      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile code
        run: g++ main.cpp -o main

      - name: Run program
        run: ./main